- .github/workflows/continuous-integration.yml
this ensures we get the right database
> fix(continuous-integration): run setup in test environment

- .github/workflows/continuous-integration.yml
allow passing
with:
redis: true
to workflows if they are to use redis
> feat(workflows): support redis in continuous-integration workflow

- .github/workflows/release-and-push-docker-image.yml
- .github/workflows/release-please.yml
have tested it with e2e-service .. it works!!
> feat(workflows): add a workflow to build and push a Docker image

- .github/workflows/release-and-push-docker-image.yml
- .github/workflows/release-please.yml
tested with developer-service - it works!
> feat(workflows): use target-branch for release

- .github/workflows/build-and-push-docker-image.yml
so that it can be used independently.
have tested with e2e-service
> feat(workflows): separate build/push from release

- .github/workflows/build-and-push-docker-image.yml
this will allow us to check out from a branch, eg 'glooko' for hedia-server.
tested with hedia-server 😊
> fix(workflows): allow checking out from a different branch

- .github/workflows/eslint.yml
- .github/workflows/prettier.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/test.yml
- .github/workflows/typescript.yml
Examples:
- hedia-team/id-service#68
- hedia-team/json#48
> feat: add individual CI workflows

- .github/workflows/update-please.yml
allows us to do this when running the workflow from a manual trigger:
> feat(update-please): add target input parameter (default to minor)

- .github/workflows/assign-to-project.yml
this is how we array in yaml :)
> ci(workflows): update for style

- .github/workflows/approve-please.yml
`gh search prs` is rubbish at filtering checks.
> fix(approve-please): delay the checks check and use `gh pr view` to do it

- .github/workflows/update-please.yml
Here is an example hedia-team/id-service#191
> feat(update-please): run npm audit fix

- .github/actions/create-pull-request/action.yml
Here is an example https://github.com/hedia-team/id-service/pull/200
> fix(update-please): check all PRs status

- .github/actions/create-pull-request/action.yml
[Example](https://github.com/hedia-team/oauth2-service/actions/runs/9761297921/job/26942021690)
> fix(create-pull-request): wrap variables with quotes

- .github/actions/set-labels/action.yml
- .github/workflows/approve-please.yml
- .github/workflows/update-please.yml
it's a special type that release-please considers a candidate for releases.
> feat: label update-please PRs as type deps

- .github/workflows/bulk-update-please.yml
- .github/workflows/update-please.yml
Counterpart: https://github.com/hedia-team/id-service/pull/252 (and we'll need a similar / identical change in the other repos too)
Fixes #34
> feat: add package filter to [bulk-]update-please

- .github/workflows/bulk-update-please.yml
- .github/workflows/ci-sonarcloud.yml
- .github/workflows/ci-test.yml
- .github/workflows/release-please.yml
tested and it works! on modules, services, config and with or without database.
> feat: take the test report from the PR and attach it to the release

- .github/workflows/release-please.yml
now it will go Features, Refactor, Bug Fixes, Dependencies.
Closes #96
> feat: Include refactor in release notes

- .github/workflows/issue.yml
This should never have been on the shared workflow. It is correctly on the self-issue workflow.
> fix: Remove issue trigger

- .github/workflows/release-please.yml
As a consequence, all changes regardless of their importance will be releasable.
> feat(release-please): List all changes made to a repo in the changelog

- .github/workflows/update-please.yml
This will allow us to see exactly what is being updated in the PR title and description.
Example with just 1 update: https://github.com/hedia-team/train-service/pull/137
Example with multiple updates: https://github.com/hedia-team/train-service/pull/136
These PRs got merged to the test branches because there was no branch protection rule. They were just for testing purposes.
> feat: Add additional details to Update Please

- .github/workflows/ci-pg-tools.yml
If we forget to run any of the PG Tools (pg-migrate, pg-inspect, or pg-docs), this workflow should make us aware of the mistake.
This closes hedia-team/dsb-team#37.
> feat: Add workflow to verify files made by PG Tools
